User.create(email: 'user1@email.com', company_name: 'User 1', password: 'Pass1!')
User.create(email: 'user2@email.com', company_name: 'User 2', password: 'Pass1!')
User.create(email: 'user3@email.com', company_name: 'User 3', password: 'Pass1!')

Coverage.create(user_id: 1)
Coverage.create(user_id: 2)
Coverage.create(user_id: 2)
Coverage.create(user_id: 3)
Coverage.create(user_id: 3)
Coverage.create(user_id: 3)

Employee.create(user_id: 1, first_name: "User 1 Employe")
Employee.create(user_id: 2, first_name: "User 2 Employe")
Employee.create(user_id: 2, first_name: "User 2 Employe")
Employee.create(user_id: 3, first_name: "User 3 Employe")
Employee.create(user_id: 3, first_name: "User 3 Employe")
Employee.create(user_id: 3, first_name: "User 3 Employe")

Role.create(user_id: 1, name: "User 1 Role")
Role.create(user_id: 2, name: "User 2 Role")
Role.create(user_id: 2, name: "User 2 Role")
Role.create(user_id: 3, name: "User 3 Role")
Role.create(user_id: 3, name: "User 3 Role")
Role.create(user_id: 3, name: "User 3 Role")

Schedule.create(user_id: 1)
Schedule.create(user_id: 2)
Schedule.create(user_id: 2)
Schedule.create(user_id: 3)
Schedule.create(user_id: 3)
Schedule.create(user_id: 3)